export const MentalHealthQuotes = [
  'Reminder that you are great, you are enough, and your presence is valued. If you are struggling with your mental health, please reach out to someone you love and consult a professional. You are not alone; there is a large range of resources online for support and guidance.',
  'There is hope, even when your brain tells you there isn’t.',
  'Things not to say to someone with mental illness: Ignore it. Forget about it. Fight it. You are better than this. You are over thinking.',
  'Being able to be your true self is one of the strongest components of good mental health',
  'All stress, anxiety, depression, is caused when we ignore who we are, and start living to please others.',
  'We would never tell someone with a broken leg that they should stop wallowing and get it together. We don’t consider taking medication for an ear infection something to be ashamed of. We shouldn’t treat mental health conditions any differently.',
  'There is no normal life that is free of pain. It’s the very wrestling with our problems that can be the impetus for our growth.',
  'You are not alone. You are seen. I am with you. You are not alone.',
  'You don’t have to control your thoughts. You just have to stop letting them control you.',
  'You, yourself, as much as anybody in the entire universe, deserve your love and affection.',
  'The best way out is always through.',
  'Vulnerability sounds like truth and feels like courage. Truth and courage aren’t always comfortable, but they’re never weakness',
  'In the middle of winter I at last discovered that there was in me an invincible summer',
  'When you take care of yourself, you’re a better person for others. When you feel good about yourself, you treat others better',
  'Mental health problems don’t define who you are. They are something you experience. You walk in the rain and you feel the rain, but, importantly, you are not the rain',
  'You are not your illness. You have an individual story to tell. You have a name, a history, a personality. Staying yourself is part of the battle',
  'Love belongs to the people who feel they are not enough. Love belongs to the kids who grow up wondering why they’re different. Love belongs to the person reading this right now. Love is for everyone',
  'Self-care is one of the active ways that I love myself. When you can and as you can, in ways that feel loving, make time and space for yourself',
  'As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others',
  'Slow, deep breathing is important… It’s like an anchor in the midst of an emotional storm: the anchor won’t get rid of the storm, but it will hold you steady until it passes',
  'Rest and self-care are so important. When you take time to replenish your spirit, it allows you to serve others from the overflow. You cannot serve from an empty vessel',
];
