/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const MentalHealthQuoteLazyImport = createFileRoute('/mental-health/quote')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MentalHealthQuoteLazyRoute = MentalHealthQuoteLazyImport.update({
  path: '/mental-health/quote',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/mental-health/quote.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/mental-health/quote': {
      id: '/mental-health/quote'
      path: '/mental-health/quote'
      fullPath: '/mental-health/quote'
      preLoaderRoute: typeof MentalHealthQuoteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MentalHealthQuoteLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mental-health/quote"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/mental-health/quote": {
      "filePath": "mental-health/quote.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
