export const MentalHealthQuotes = [
  "Reminder that you are great, you are enough, and your presence is valued. If you are struggling with your mental health, please reach out to someone you love and consult a professional. You are not alone; there is a large range of resources online for support and guidance.",
  "There is hope, even when your brain tells you there isn’t.",
  "Things not to say to someone with mental illness: Ignore it. Forget about it. Fight it. You are better than this. You are over thinking.",
  "Being able to be your true self is one of the strongest components of good mental health",
  "All stress, anxiety, depression, is caused when we ignore who we are, and start living to please others.",
  "We would never tell someone with a broken leg that they should stop wallowing and get it together. We don’t consider taking medication for an ear infection something to be ashamed of. We shouldn’t treat mental health conditions any differently.",
  "There is no normal life that is free of pain. It’s the very wrestling with our problems that can be the impetus for our growth.",
  "You are not alone. You are seen. I am with you. You are not alone.",
  "You don’t have to control your thoughts. You just have to stop letting them control you.",
  "You, yourself, as much as anybody in the entire universe, deserve your love and affection.",
  "The best way out is always through.",
  "Vulnerability sounds like truth and feels like courage. Truth and courage aren’t always comfortable, but they’re never weakness",
  "In the middle of winter I at last discovered that there was in me an invincible summer",
  "When you take care of yourself, you’re a better person for others. When you feel good about yourself, you treat others better",
  "Mental health problems don’t define who you are. They are something you experience. You walk in the rain and you feel the rain, but, importantly, you are not the rain",
  "You are not your illness. You have an individual story to tell. You have a name, a history, a personality. Staying yourself is part of the battle",
  "Love belongs to the people who feel they are not enough. Love belongs to the kids who grow up wondering why they’re different. Love belongs to the person reading this right now. Love is for everyone",
  "Self-care is one of the active ways that I love myself. When you can and as you can, in ways that feel loving, make time and space for yourself",
  "As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others",
  "Slow, deep breathing is important... It’s like an anchor in the midst of an emotional storm: the anchor won’t get rid of the storm, but it will hold you steady until it passes",
  "Rest and self-care are so important. When you take time to replenish your spirit, it allows you to serve others from the overflow. You cannot serve from an empty vessel",
  "Your mental health is a priority. Your happiness is an essential. Your self-care is a necessity.",
  "Healing is not linear. It’s okay to take a step back and reassess. Progress comes with patience and compassion for yourself.",
  "You have been criticizing yourself for years and it hasn’t worked. Try approving of yourself and see what happens.",
  "It’s okay to ask for help. It’s okay to not be okay. You are human, and your feelings are valid.",
  "Small steps every day. That’s how healing happens. You don’t have to climb the whole mountain at once.",
  "Mental health is not a destination, but a process. It’s about how you drive, not where you’re going.",
  "You don’t have to struggle in silence. Reach out, speak up, and let someone in.",
  "Take time to make your soul happy. Protect your energy and nourish your peace.",
  "Every day may not be good, but there is something good in every day.",
  "Be kind to yourself. You’re doing the best you can with what you have and that is enough.",
  "A smile can brighten your darkest day. Let it shine and spread joy.",
  "Find joy in the little things, because every moment is a chance to smile.",
  "Happiness is a journey, not a destination. Enjoy every step along the way.",
  "You have the power to light up the world with your genuine smile.",
  "Every sunrise brings a new opportunity to create happiness and embrace joy.",
  "When you embrace your inner light, nothing can dim your radiance.",
  "Celebrate small victories, for they build a life full of joy and wonder.",
  "A grateful heart is a magnet for miracles. Keep smiling and believing.",
  "Joy is contagious and you have the power to spread it wherever you go.",
  "Embrace the magic of every day, because life is full of beautiful moments.",
  "Your smile is a powerful reminder that there is always hope and happiness.",
  "Nurture your soul with positivity, love and laughter—it’s the recipe for a happy life.",
  "Allow joy to be the soundtrack of your life and let love be your guide.",
  "Every challenge is an opportunity to grow, smile and overcome.",
  "Let your inner beauty shine, and fill the world with colorful joy.",
  "Happiness doesn’t require a reason. Sometimes you just choose to smile.",
  "The world is brighter when you choose positivity and spread love.",
  "Fill your days with joy, laughter and endless possibilities.",
  "You are a beacon of light in a sometimes dark world. Shine bright, and share your smile.",
  "Every moment holds a promise of happiness—if you let it come in.",
  "Smile often, love freely, and live boldly, for life is too beautiful not to.",
  "Find the beauty in every day, and let it fill your heart with joy.",
  "Happiness is found in everyday moments. Embrace them with a smiling heart.",
  "A joyful heart radiates warmth, love and endless positivity.",
  "Let your smile be the sunshine that brightens someone’s day.",
  "You deserve happiness and unconditional joy. Never doubt your worth.",
  "Celebrate your unique journey and find joy in every twist and turn of life.",
  "Your positive energy is a gift. Share it generously and watch it multiply.",
  "Allow yourself to laugh freely, and cherish the moments that bring you joy.",
  "Remember, every day is a new beginning filled with hope, love and endless possibilities.",
];
